# Definición de las etapas del pipeline
stages:
  - install
  - test
  - build
  - deploy

# Variables globales
variables:
  NODE_VERSION: "18-alpine"

# Cache para node_modules y dist
cache:
  paths:
    - node_modules/
    - dist/

# Job para instalar dependencias
install:
  stage: install
  image: node:${NODE_VERSION}
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Job para ejecutar tests
test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm run test
    - npm run test:e2e
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - install

# Job para análisis de código
lint:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm run lint
  dependencies:
    - install

# Job para compilar la aplicación
build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install

# Job para despliegue en desarrollo
deploy_dev:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - echo "Desplegando en ambiente de desarrollo..."
    # Aquí irían los comandos de despliegue específicos
  environment:
    name: development
  only:
    - develop
  dependencies:
    - build

# Job para despliegue en producción
deploy_prod:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - echo "Desplegando en ambiente de producción..."
    # Aquí irían los comandos de despliegue específicos
  environment:
    name: production
  only:
    - main
  when: manual
  dependencies:
    - build