stages:
  - install
  - test
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  CACHE_FOLDER: '.npm'
  DIST_FOLDER: 'dist'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${CACHE_FOLDER}/

install_dependencies:
  stage: install
  image: node:18 # Cambia según la versión de Node.js que uses
  script:
    - echo "Instalando dependencias..."
    - npm install -g @nestjs/cli
    - npm ci
  artifacts:
    paths:
      - ${CACHE_FOLDER}/
