stages:
  - install
  - test
  - build

variables:
  NODE_ENV: test
  CACHE_DIR: .cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - ${CACHE_DIR}/

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

run_tests:
  stage: test
  image: node:20
  script:
    - npm run test
  dependencies:
    - install_dependencies

build_app:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  dependencies:
    - install_dependencies
